# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Wpy7uxtgnfgzObO5u2-_-GdR2Z1o9K1
"""


# !nvidia-smi

"""The below line is required as Hugging Face Diffusers on PyPi is not fully updated with StableDiffusion Pipeline. Hence we are are downloading it directly from Github. """

# !pip install https://github.com/huggingface/diffusers/archive/main.zip -qUU --force-reinstall
# !pip install -qq -U transformers ftfy
# !pip install -qq "ipywidgets>=7,<8"
# !pip install --ignore-installed "Pillow==9.0.0"
# !pip install torch requests
# !pip install numpy --upgrade
# this fixes the module 'PIL.Image' has no attribute 'Resampling' error

# Commented out IPython magic to ensure Python compatibility.
from torch import autocast
import torch
import requests
from PIL import Image
from io import BytesIO
from diffusers import StableDiffusionImg2ImgPipeline

from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)
# %cd gdrive/MyDrive

# load the pipeline
device = "cuda"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16
).to(device)

from prompts import prompts

def get_image(fname):
  init_image = Image.open(fname).convert("RGB")
  init_image = init_image.resize((768, 512))
  return init_image.rotate(180, Image.NEAREST, expand = 1)

for i in range(1103):
  fname = f"./convert/frame_{i+1}.jpg"
  prompt = prompts[i//10]
  image = get_image(fname)

  with autocast("cuda"):
    images = pipe(prompt=prompt, image=image, strength=0.5, guidance_scale=16,num_images_per_prompt=1)
  images[0][0].save(f"./output/{str(i)}.jpg")

